### ISSUE TITLE
SyntaxError: Non-ASCII character line 15

### ISSUE THREAD

**Issue by macrupy** [mh-Earth/Instaploit#1]
File "instaploit.py", line 15
SyntaxError: Non-ASCII character '\xef' in file instaploit.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
![Screenshot_2021-02-26-03-11-55-188_com.termux.jpg](https://user-images.githubusercontent.com/73712384/109211221-843e7f00-77e0-11eb-8887-3cedfee475d6.jpg)

**Comment by mh-Earth** [comment]
fix encoding error
